name: GH200-Training

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "hello world"

      - name: copy code
        uses: actions/checkout@v6

      - name: List repo Files
        run: ls -la





